FROM node:lts-slim as builder
WORKDIR /var/app
COPY . ./

RUN yarn global add typescript
RUN yarn install

RUN yarn build

FROM node:lts-slim as main
WORKDIR /var/app

COPY --from=builder /var/app/dist/ ./dist/
COPY --from=builder /var/app/config/ ./config/
COPY --from=builder /var/app/package.json ./
COPY --from=builder /var/app/yarn.lock ./

RUN yarn install --prod

EXPOSE 20000
CMD [ "yarn", "start" ]